### ISSUE TITLE
JOSS review: Installation

### ISSUE THREAD

**Issue by DamienIrving** [miniufo/xinvert#16]
@miniufo - well done on your submission to JOSS.

As part of my review of your submission (see https://github.com/openjournals/joss-reviews/issues/5510), I have some questions/suggestions regarding software installation:
- In the "how to install" (https://github.com/miniufo/xinvert#2-how-to-install) section of your README file it says "install via pip (not yet)" but as far as I can tell it can be installed by pip. What is the meaning of "not yet"?
- Do you think it would be advantageous to also make the package available via conda (i.e. conda-forge) for users who manage their python environments using conda?

**Comment by miniufo** [comment]
- that's right.  I forgot to update this.  (not yet) should be removed.
- Definitely should be in conda.  Right now I send a PR to conda for another package [here](https://github.com/conda-forge/staged-recipes/pull/22849), which is the first time I do this.  I am not sure how long it would take (or maybe I do something incorrect).  Maybe you can point me to the right path on how to make `xinvert` available via conda.

**Comment by DamienIrving** [comment]
Your xgrads PR looks fine to me - hopefully they will action it soon.

Since xinvert is available via pip I don't think waiting for it to be available via conda should delay your JOSS publication. It would be nice to have it available via conda eventually, but it's not absolutely necessary for publication with JOSS.

**Comment by miniufo** [comment]
That's great.  I'll follow the steps of xgrads and make a PR of adding xinvert to conda recipe.

**Comment by miniufo** [comment]
Hi @DamienIrving, I've removed **'not yet'** in the [README.md](https://github.com/miniufo/xinvert).  Also, I've sent a PR to [conda recipe](https://github.com/conda-forge/staged-recipes/pull/23082), waiting it to be merged.  Please see if this issue is fixed now.

**Comment by DamienIrving** [comment]
Awesome. Thanks, @miniufo.
