### ISSUE TITLE
JOSS review: community guidelines

### ISSUE THREAD

**Issue by DamienIrving** [miniufo/xinvert#18]
@miniufo - well done on your submission to JOSS.

As it stands, your package doesn't meet the following requirement on the reviewer checklist:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

(See https://github.com/openjournals/joss-reviews/issues/5510 for details.)

**Comment by miniufo** [comment]
Ops, I should add this too.

**Comment by miniufo** [comment]
I've added a page to the doc [here](https://xinvert.readthedocs.io/en/latest/Contributors.html).  Please see if this is OK.
