### ISSUE TITLE
JOSS review: state of the field

### ISSUE THREAD

**Issue by DamienIrving** [miniufo/xinvert#19]
@miniufo - well done on your submission to JOSS.

There is a requirement on the reviewer checklist relating to the software paper which reads as follows:
> State of the field: Do the authors describe how this software compares to other commonly-used packages?

(See https://github.com/openjournals/joss-reviews/issues/5510 for details.)

You make a comparison against windspharm in your README file...
> Inversion on the spherical earth, like some meteorological problems, could utilize the spherical harmonics like [windspharm](https://github.com/ajdawson/windspharm), which would be more efficient using FFT than SOR used here. However, in the case of ocean, SOR method is definitely a better choice in the presence of irregular land/sea mask.

... but not in the software paper itself. I think it would be worth mentioning windspharm (and any other relevant commonly-used packages) in your software paper too.

**Comment by miniufo** [comment]
Thank you very much @DamienIrving,  yes I missed this, and I will add a paragraph describing the state of the field.

**Comment by miniufo** [comment]
I've add one paragraph [here](https://github.com/miniufo/xinvert/blob/master/paper/paper.md#state-of-the-field) to address the state of the field.  Please see if it is OK now.

**Comment by DamienIrving** [comment]
Perfect!
