### ISSUE TITLE
Software paper: Citation of python packages

### ISSUE THREAD

**Issue by NoraLoose** [miniufo/xinvert#22]
To cite the packages windspharm and Dedalus, please use the citations to the software papers (rather than just linking to the package github repos):

- [ ] https://openresearchsoftware.metajnl.com/articles/10.5334/jors.129
- [ ] https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.2.023068

This is part of the JOSS review process at https://github.com/openjournals/joss-reviews/issues/5510.

**Comment by miniufo** [comment]
Thanks for your suggestion.  I should change the citations to these two packages.

**Comment by miniufo** [comment]
Hi @NoraLoose, the citations are updated.  The newly-generated PDF is at [here](https://github.com/openjournals/joss-papers/blob/joss.05510/joss.05510/10.21105.joss.05510.pdf).  Please check this.

**Comment by NoraLoose** [comment]
Great, thanks! I'm closing this issue.
