### ISSUE TITLE
invert_omega: Need to pass N2 and f0 as dataArrays

### ISSUE THREAD

**Issue by hs2112** [miniufo/xinvert#30]
Hi,

Is it possible to pass different values of N2 per pressure level, and f0 per latitude, in the form of coordinate-aware arrays? In particular, N2 is quite different for the upper and lower levels. 

Thanks!

**Comment by miniufo** [comment]
Hi, of course yes.  f0 is specified on beta plane.  So if the forcing is defined on a lat/lon grid, then you don't need to provide f0, which is overlooked in lat/lon case.  N2(k) should be defined as the same as forcing function in the vertical.

**Comment by miniufo** [comment]
The true f will be calculated automatically according to your latitude definitions wrapped in the forcing function.

**Comment by hs2112** [comment]
Since the equation is solving for the following,
```math
\frac{1}{\partial x}\left(N^2\frac{\partial \omega}{\partial x}\right)+
\frac{1}{\partial y}\left(N^2\frac{\partial \omega}{\partial y}\right) + 
\frac{1}{\partial z}\left(f^2\frac{\partial \omega}{\partial z}\right)=F
```
and not,
```math
\left(N^2 \nabla_p ^2 + f^2\frac{\partial ^2}{\partial p^2}\right)\omega = F
```

which is the desired omega equation. So I am planning to set $`N^2`$ as 1 and replace $`f0`$ with $`f0/\sqrt(N^2)`$ as a workaround even though it is not a perfect solution as $`N^2`$ gets differentiated in the vertical. 

1. Is it possible to solve the latter equation directly?
2. "N2(k) should be defined as the same as forcing function in the vertical." - just to confirm, you mean I can pass a dataarray of N2 with the same dim/coords as the frocing function?

**Comment by hs2112** [comment]
Yes, that makes sense. I had missed that you are using an array for the stability parameter in your example, so that solves my issue. Thank you. 

Even though that wasn't my initial question, I would want to let $`N^2`$ vary with y.

**Comment by miniufo** [comment]
Yes, in your case of $N(y, z)$, one cannot derive the traditional form as your second equation above.  The exact form when $N$ is a 3D variable is not as simple as one may expect.  I guess the first one is not correct neither, except you can derive it from the very start (you may use $N(z)$ as a condition in the derivation).  This is what I can recall right now.

But if you want a try with solving the first equation above, then $N$ can be varying both horizontally and vertically, which fits the solver of xinvert.

**Comment by hs2112** [comment]
Yes, I suspected that. Will see what resultant equation I get, deriving with $`N^2(y,z)`$.

**Comment by miniufo** [comment]
I have [a notebook here](https://github.com/miniufo/xinvert/blob/master/docs/source/notebooks/11_Omega_equation.ipynb) and the derived Eq. (14) is:
![1695222685858](https://github.com/miniufo/xinvert/assets/9312831/8a795b7e-edb1-48bd-a8e2-6045de9b9c1c)

So the $N^2$ (here it is $S$ ) is inside the Laplacian, which is slightly different from your first equation.  To invert this, one may choose the general form rather than standard form.  But I am also curious about how large the differences are when using your first equation above and the one shown here.

**Comment by miniufo** [comment]
Close this now and feel free to re-open it in any case.
