### ISSUE TITLE
Lat-Lon Finite Differences

### ISSUE THREAD

**Issue by jejjohnson** [miniufo/xinvert#32]
Hi, this package looks really neat! 

I was wondering if you had a reference for how you are calculating the finite differences with spherical coordinates? From the looks of it, you’re simply multiplying the Y-axis by a scalar factor of degrees to meters and the X-axis by the same plus  and a cosine of the Y-coords. I’m not familiar with this but this seems really, really useful in general with finite differences for lat-lon.

Do you have a reference or something I could look at because I’m not familiar with this but I would really like to use it.

Thanks!

**Comment by miniufo** [comment]
Hi, thanks for your interests.  This is just a simple centered finite difference for lat-lon grids.  I guess you can find the differential operators in spherical coordinates in a textbook like dynamic meteorology or geophysical fluid dynamics.  I had a clip for your convenience:
![1696321956249](https://github.com/miniufo/xinvert/assets/9312831/1ed30169-84db-47d1-8490-91c9bad4af64)

- For a scalar, its meridional gradient (second line) does not need the cosine weighting;
- For a vector, its meridional divergence (third line) does require cosine weighting.

**Comment by jejjohnson** [comment]
Thank you very much! I have a quick question: why is the [wikipedia article](https://en.wikipedia.org/wiki/Spherical_coordinate_system#Integration_and_differentiation_in_spherical_coordinates) consistently have a `sin` instead of a `cos`? Is this because of the typical bounds? Or am I missing something more fundamental and/or subtle?

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/175f5c757bb3e3aadcdd97cfd4c7953fa98379e3)

**Comment by miniufo** [comment]
Close this now and feel free to re-open it in any case.
